#!/usr/bin/env python
#-*- coding: utf-8 -*-

name_dict = {
    'ChoYoungwhan': ('조 영환님', '1'),
    'HanSangjik': ('한 상직님', '1'),
    'HwangDaewon': ('황 대원님', '1'),
    'HwangHyungjae': ('황 형재님', '1'),
    'JangTaejin': ('장 태진님', '1'),
    'JangYoonseok': ('장 윤석님', '1'), 
    'KimDaeseoung': ('김 대승님', '1'),
    'KimDongjin': ('김 동진님', '1'),
    'KimHaeri': ('김 해리님', '1'),
    'KimJinhyung': ('김 진형님', '1'), 
    'KimKeeyoung': ('김 기영님', '1'), 
    'KimMina': ('김 미나님', '1'), 
    'KimSeokwon': ('김 석원님', '1'), 
    'KimSeongpyo': ('김 성표님', '1'),
    'KoAhra': ('고 아라님', '1'), 
    'LeeIlkyu': ('이 일규님', '1'),
    'LeeKwanghee': ('이 광희님', '1'), 
    'LeeManjae': ('이 만재님', '1'),
    'LeeSanghun': ('이 상훈님', '1'),
    'LeeSanghwa': ('이 상화님', '1'),
    'LeeYoungtae': ('이 영태님', '1'),
    'LeeYuni': ('이 유니님', '1'),
    'MoonSeungjin': ('문 승진님', '1'),
    'ParkDaeyoung': ('박 대영님', '1'),
    'ParkSangsik': ('박 상식님', '1'),
    'SeoByungrak': ('서 병락님', '1'),
    'SeoKiho': ('서 기호님', '1'),
    'SeoKyungjin': ('서 경진님', '1'),
} 
